openapi: 3.0.0
info:
  title: Simple Developer API
  description: Developers API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://127.0.0.1:4010
- url: https://virtserver.swaggerhub.com/max396/exmple2/1.0.0
  description: Devlopers REST API
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /developers:
    get:
      tags:
      - developers
      summary: searches all developers
      description: |
        모든 개발자들을 조회합니다
      operationId: searchInventory
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Developer'
              example:
              - id: 0
                name: 김종혁
                age: 26
                position: frontend
                major: 영문학
              - id: 1
                name: 황인준
                age: 26
                position: backend
                major: 정보시스템
        "400":
          description: bad input parameter
    post:
      tags:
      - developers
      summary: Add new Developer
      description: 새로운 개발자를 추가합니다
      operationId: addInventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Developer'
            example:
            - id: 2
              name: 최범수
              age: 26
              position: frontend
              major: 컴퓨터공학
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
components:
  schemas:
    Developer:
      required:
      - age
      - id
      - major
      - name
      - position
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: 김성익
        age:
          type: integer
          example: 25
        position:
          type: string
          example: devops
          enum:
          - frontend
          - backend
          - devops
        major:
          type: string
          example: 정보시스템
